name: app3
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bot_toast: ^4.0.1
  provider: ^6.0.2
  easy_localization: ^3.0.0
  chaotic: ^3.10.8
  cloud_firestore: ^3.1.6
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cached_network_image: ^3.2.0
  animate_do: ^2.1.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  chaotic_helper:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
